// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abknuckftzdncxigqdek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFia251Y2tmdHpkbmN4aWdxZGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzY4ODYsImV4cCI6MjA3Mzc1Mjg4Nn0.Q6J7-FiUZjgvHMFJuBCqQhVgKbeytfjnRAo34oCowfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});